apiVersion: v1
kind: Secret
metadata:
  name: mode-wle-signer-secrets
stringData:
  # Add your secret data here
  otlp-headers: x-honeycomb-team=MY_HONEYCOMB_API_KEY
  mode-team: MY_MODE_TEAM
  mode-access-key: MY_MODE_ACCESS_KEY
  mode-access-secret: MY_MODE_ACCESS_SECRET
  token: MY_TOKEN
